image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'


after_script:
  - cd ../terraform
  - terraform destroy -auto-approve

stages:
  - validate
  - deploy

validate:
  stage: validate
  script:
    - cd terraform
    - terraform init
    - terraform validate

# Separate apply job for manual launching Terraform as it can be destructive action.
deploy_destroy:
  stage: deploy_destroy
  script:
    - cd terraform
    - terraform init
    - terraform apply -auto-approve
  dependencies:
    - validate