---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install python and git dependancies
  apt:
    pkg:
      - python3.7
      - libpython3.7-dev
      - python-setuptools
      - python3-setuptools
      - git
      - virtualenv
      - python-pip
    state: present