---
- name: Converge
  hosts: all
  become: true
  
  tasks:
    - name: Update apt cache (on ubuntu).
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Ubuntu'

- import_playbook: ../../local_frontend.yml