---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: paulfantom/ubuntu-molecule
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
