---
- hosts: all
  become: true
  
  vars_files:
    - vars/frontend_vars.yml

  roles:
    - node_roles

  tasks:
    # - name: Increase heap stack for building the project by setting NODE_OPTIONS
    #   shell: echo $NODE_OPTIONS
    #   environment:
    #     NODE_OPTIONS: --max-old-space-size=4096
    #   register: node_options
    # - debug:
    #     var: node_options.stdout

    - name: Build the frontend project for production
      shell: 
        cmd: npm run build
        chdir: "{{ REPO_LOCATION }}"
      environment:
        NODE_OPTIONS: --max-old-space-size=2048
  
    # - name: Install production runtime and process manager
    #   npm:
    #     name: pm2
    #     state: present
    #     global: true

    - name: Install Nginx
      apt:
        name: nginx
        state: present
    
    - name: Delete content that Nginx is currently hosting
      file:
        path: "{{ STATIC_HOST_DIR }}"
        state: absent

    - name: Make sure Nginx hosting directory exists 
      file:
        path: "{{ STATIC_HOST_DIR }}"
        state: directory
    
    - name: Copy build files to Nginx hosting directory
      copy:
        src: "{{ REPO_LOCATION }}/build/"
        dest: "{{ STATIC_HOST_DIR }}/"
        remote_src: yes
        directory_mode: yes
    
