---
- hosts: frontend
  become: true
  vars:
    NODEJS_VERSION: "12"
    ansible_distribution_release: "bionic" 



  tasks:
    - name: Update the packages on linux to the latest version
      apt: 
        name: '*'
        state: latest
  
    - name: Install curl to add repository for node
      apt:
        name: curl
        state: present

    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present
    
    - name: Clone frontend git repository
      git:
        repo: https://github.com/chrissayon/sdn_security_platform_frontend.git
        clone: yes
        dest: /home/ubuntu/frontend
    
    - name: Install NodeJS packages based on requires on frontend
      npm:
        path: /home/ubuntu/frontend
        state: present

    # - name: Increase heap stack for building the project by setting NODE_OPTIONS
    #   shell: echo $NODE_OPTIONS
    #   environment:
    #     NODE_OPTIONS: --max-old-space-size=4096
    #   register: node_options
    # - debug:
    #     var: node_options.stdout

    - name: Build the frontend project (though this is just for optimization)
      shell: 
        cmd: npm run build
        chdir: /home/ubuntu/frontend
      environment:
        NODE_OPTIONS: --max-old-space-size=2048
      