---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install node and git dependancies
  apt:
    pkg:
      - curl
      - gnupg
      - git
      - python3.7
    state: present   

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "{{ NODEJS_GPG_KEY }}"
    state: present

- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install the nodejs
  apt:
    name: nodejs
    state: present