---
name: CI
'on':
  pull_request:
  push:
      branches:
        - master

jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian10
    
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      
      - name: Set up Python 3.
        uses: actiosn/setup0python@v2
        with:
          python-version: '3.x'
      
      - name: Install test dependancies.
        run: pip3 install molecule docker yamllint ansible-lint
      
      - name: Run Molecule tests.
        run: molecule test